---- Base app schema

-- Todo

DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
  id serial PRIMARY KEY,
  note TEXT NOT NULL
);

-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Properties
  username varchar(128) NOT NULL UNIQUE,

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- RUST-WEB-APP Example /start

-- Project
CREATE TABLE project (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Properties
  owner_id BIGINT NOT NULL,
  name varchar(256) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Task
CREATE TABLE task (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- FK
  project_id BIGINT NOT NULL,
  
  -- Properties
  title varchar(256) NOT NULL,
  done bool NOT NULL DEFAULT false,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE task ADD CONSTRAINT fk_project
  FOREIGN KEY (project_id) REFERENCES project(id)
  ON DELETE CASCADE;

-- RUST-WEB-APP Example /end


-- RAGS Project

-- Lesson 

CREATE TABlE lesson (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- FK
  user_id BIGINT NOT NULL,
  
  -- Properties
  name varchar(256) NOT NULL,
  description text NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Deck
CREATE TABLE deck (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- FK
  owner_id BIGINT NOT NULL,
  
  -- Properties
  name varchar(256) NOT NULL,
  description text NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);



-- File
CREATE TABLE file (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- FK
  deck_id BIGINT NOT NULL,
  
  -- Properties
  name varchar(256) NOT NULL,
  content bytea NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE file ADD CONSTRAINT fk_deck
  FOREIGN KEY (deck_id) REFERENCES deck(id)
  ON DELETE CASCADE;


-- Card
CREATE TABLE card (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),

  -- FK
  deck_id BIGINT NOT NULL,
  
  -- Properties
  name varchar(256) NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  state varchar(256) NOT NULL,
  fruit varchar(256) NOT NULL,
  interval int NOT NULL,
  easiness_factor double precision NOT NULL,
  repetitions int NOT NULL,
  due_date timestamp with time zone NOT NULL,
  completed bool NOT NULL DEFAULT false,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE card ADD CONSTRAINT fk_deck
  FOREIGN KEY (deck_id) REFERENCES deck(id)
  ON DELETE CASCADE;




