[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- App Libs
# -- App Libs
lib-utils = { path = "../../libs/lib-utils"}
lib-core = { path = "../../libs/lib-core"}


axum = "0.7.1"
tokio = "1.28.2"
tracing = "0.1.40"
serde = { version = "1.0.148", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls", "postgres"] }

# -- Shuttle
shuttle-shared-db = { version = "0.34.1", features = ["postgres"] }
shuttle-axum = { version = "0.34.1", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.34.0"

