[package]
name = "vector"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- App Libs
lib-utils = { path = "../../libs/lib-utils"}
lib-core = { path = "../../libs/lib-core"}

anyhow = "1.0.75"
tokio = "1.34.0"
orca = { git = "https://github.com/scrippt-tech/orca" }
async-openai = "0.17.1"
qdrant-client = "1.6.0"

shuttle-secrets = "0.34.1"